/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BandejaRouteRouteImport } from './routes/bandeja/route'
import { Route as AccesoIndexRouteImport } from './routes/acceso/index'
import { Route as BandejaIndexRouteImport } from './routes/bandeja/index'
import { Route as BotIndexRouteImport } from './routes/bot/index'
import { Route as ConfiguracionIndexRouteImport } from './routes/configuracion/index'
import { Route as ContactosIndexRouteImport } from './routes/contactos/index'
import { Route as BandejaChatIdChatRouteImport } from './routes/bandeja/chat/$idChat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRouteRoute = BandejaRouteRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoIndexRoute = AccesoIndexRouteImport.update({
  id: '/acceso/',
  path: '/acceso/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaIndexRoute = BandejaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BandejaRouteRoute,
} as any)
const BotIndexRoute = BotIndexRouteImport.update({
  id: '/bot/',
  path: '/bot/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionIndexRoute = ConfiguracionIndexRouteImport.update({
  id: '/configuracion/',
  path: '/configuracion/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIndexRoute = ContactosIndexRouteImport.update({
  id: '/contactos/',
  path: '/contactos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaChatIdChatRoute = BandejaChatIdChatRouteImport.update({
  id: '/chat/$idChat',
  path: '/chat/$idChat',
  getParentRoute: () => BandejaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bandeja': typeof BandejaRouteRouteWithChildren
  '/acceso/': typeof AccesoIndexRoute
  '/bandeja/': typeof BandejaIndexRoute
  '/bot/': typeof BotIndexRoute
  '/configuracion/': typeof ConfiguracionIndexRoute
  '/contactos/': typeof ContactosIndexRoute
  '/bandeja/chat/$idChat': typeof BandejaChatIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoIndexRoute
  '/bandeja': typeof BandejaIndexRoute
  '/bot': typeof BotIndexRoute
  '/configuracion': typeof ConfiguracionIndexRoute
  '/contactos': typeof ContactosIndexRoute
  '/bandeja/chat/$idChat': typeof BandejaChatIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bandeja': typeof BandejaRouteRouteWithChildren
  '/acceso/': typeof AccesoIndexRoute
  '/bandeja/': typeof BandejaIndexRoute
  '/bot/': typeof BotIndexRoute
  '/configuracion/': typeof ConfiguracionIndexRoute
  '/contactos/': typeof ContactosIndexRoute
  '/bandeja/chat/$idChat': typeof BandejaChatIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bandeja'
    | '/acceso/'
    | '/bandeja/'
    | '/bot/'
    | '/configuracion/'
    | '/contactos/'
    | '/bandeja/chat/$idChat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/bandeja'
    | '/bot'
    | '/configuracion'
    | '/contactos'
    | '/bandeja/chat/$idChat'
  id:
    | '__root__'
    | '/'
    | '/bandeja'
    | '/acceso/'
    | '/bandeja/'
    | '/bot/'
    | '/configuracion/'
    | '/contactos/'
    | '/bandeja/chat/$idChat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandejaRouteRoute: typeof BandejaRouteRouteWithChildren
  AccesoIndexRoute: typeof AccesoIndexRoute
  BotIndexRoute: typeof BotIndexRoute
  ConfiguracionIndexRoute: typeof ConfiguracionIndexRoute
  ContactosIndexRoute: typeof ContactosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso/': {
      id: '/acceso/'
      path: '/acceso'
      fullPath: '/acceso/'
      preLoaderRoute: typeof AccesoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja/': {
      id: '/bandeja/'
      path: '/'
      fullPath: '/bandeja/'
      preLoaderRoute: typeof BandejaIndexRouteImport
      parentRoute: typeof BandejaRouteRoute
    }
    '/bot/': {
      id: '/bot/'
      path: '/bot'
      fullPath: '/bot/'
      preLoaderRoute: typeof BotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion/': {
      id: '/configuracion/'
      path: '/configuracion'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof ConfiguracionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/': {
      id: '/contactos/'
      path: '/contactos'
      fullPath: '/contactos/'
      preLoaderRoute: typeof ContactosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja/chat/$idChat': {
      id: '/bandeja/chat/$idChat'
      path: '/chat/$idChat'
      fullPath: '/bandeja/chat/$idChat'
      preLoaderRoute: typeof BandejaChatIdChatRouteImport
      parentRoute: typeof BandejaRouteRoute
    }
  }
}

interface BandejaRouteRouteChildren {
  BandejaIndexRoute: typeof BandejaIndexRoute
  BandejaChatIdChatRoute: typeof BandejaChatIdChatRoute
}

const BandejaRouteRouteChildren: BandejaRouteRouteChildren = {
  BandejaIndexRoute: BandejaIndexRoute,
  BandejaChatIdChatRoute: BandejaChatIdChatRoute,
}

const BandejaRouteRouteWithChildren = BandejaRouteRoute._addFileChildren(
  BandejaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandejaRouteRoute: BandejaRouteRouteWithChildren,
  AccesoIndexRoute: AccesoIndexRoute,
  BotIndexRoute: BotIndexRoute,
  ConfiguracionIndexRoute: ConfiguracionIndexRoute,
  ContactosIndexRoute: ContactosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
